version: "3.3"
services:
    node:
        build:
            context: ./node
    nginx:
        build:
            context: ./nginx
        ports:
            - "80:80"
    mqtt:
        build:
            context: ./mqtt
        ports:
            - "1884:1884"
            - "1883:1883"
    mysql:
        build:
            context: ./mysql
        ports:
            - "3306:3306"
            - "33060:33060"
    mongodb:
        build:
            context: ./mongodb
        ports: 
            - "27017:27017"