version: "3.3"
services:
    nodeCollect:
        build:
            context: ./nodeCollect

    nodeExpressApi:
        build:
            context: ./nodeExpressApi
        ports: 
            - "6969:6969"    

    nodeMqttBackend:
        build:
            context: ./nodeMqttBackend    

    nodeWebsocketBackend: 
        build:
            context: ./nodeWebsocketBackend
        ports:
            - "8888:8888"               

    nginx:
        build:
            context: ./nginx
        ports:
            - "80:80"
            - "8080:8080"

    mqtt:
        build:
            context: ./mqtt
        ports:
            - "1884:1884"
            - "1883:1883"

    mysql:
        build:
            context: ./mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123456    
        ports:
            - "3306:3306"
            
    mongodb:
        build:
            context: ./mongodb
        ports: 
            - "27017:27017"