version: "3.3"
services:
    nodecollect:
        container_name: nodecollect
        restart: on-failure 
        build:
            context: .
            dockerfile: ./nodecollect/Dockerfile
        #depends_on: 
            #mongodb:
            #    condition: service_healthy  
            #mqtt:
            #    condition: service_healthy  

    nodeexpressapi:
        container_name: nodeexpressapi
        restart: on-failure:5
        build:
            context: .
            dockerfile: ./nodeexpressapi/Dockerfile
        ports: 
            - "6969:6969"    
        depends_on: 
            mysql:
                condition: service_healthy     

    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        ports:
            - "80:80"
            - "8080:8080"

    mqtt:
        container_name: mqtt
        build:
            context: ./mqtt
        ports:
            - "1884:1884"
            - "1883:1883"
        #healthcheck:
        #    test: ["CMD-SHELL", "timeout -t 5 mosquitto_sub -t '$$SYS/#' -C 1 | grep -v Error || exit 1"]    
        #    interval: 10s
        #    timeout: 10s
        #    retries: 5

    mysql:
        container_name: mysql
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: a   
        ports:
            - "3306:3306"  
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=a --execute \"SHOW DATABASES;\""
            interval: 5s
            timeout: 10s
            retries: 5
            
    mongodb:
      container_name: mongodb
      image: mongo:latest
    #   environment:
    #       MONGO_INITDB_ROOT_USERNAME: root
    #       MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
        - ./mongodb:/data/db    
      ports: 
          - "27017:27017"
    #  healthcheck: 
    #    test: echo 'db.runCommand("ping").ok' | mongodb mongo:27017/test --quiet
    #    interval: 5s
    #    timeout: 10s
    #    retries: 5  
    #    start_period: 30s 

# remove volumes if error
